- name: Ensure Firefox repository is added
  become: yes
  become_user: root
  apt_repository:
    repo: "ppa:mozillateam/ppa"
    state: present

- name: Prefer Firefox DEB rather than Snap
  become: yes
  become_user: root
  copy:
    content: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001

      Package: firefox
      Pin: version 1:1snap*
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/mozilla-firefox

- name: Ensure Firefox is installed
  become: yes
  become_user: root
  apt:
    update_cache: no
    name:
      - firefox
    state: present
